name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build_and_push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build the Docker image
        run: |
          docker build -t dockerit571/project1:latest . --file Dockerfile #--tag node:$(date +%s)
          docker images

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.MY_PASSWORD }}
        
      - uses: docker/tags-action@v1
         env:|
          tag:"$latest"
        
      - name: Push Docker image to Docker Hub
        run: docker push dockerit571/project1:$tag
