name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    
jobs:

  build_and_push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build the Docker image
        run: |
          docker build -t dockerit571/project1:latest . --file Dockerfile #--tag node:$(date +%s)
          docker images

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.MY_PASSWORD }}
      - name: Generate Git Tag
        id: generate_tag
        run: |
         VERSION_PREFIX="v"
         VERSION_MAJOR_MINOR="1.0"
         VERSION_PATCH=$(git tag --list "${VERSION_PREFIX}${VERSION_MAJOR_MINOR}.*" --sort=-version:refname | head -n 1 | grep -oE '[0-9]+$')
         if [ -z "$VERSION_PATCH" ]; then
           VERSION_PATCH=0
         else
           VERSION_PATCH=$((VERSION_PATCH + 1))
         fi
         NEW_TAG="${VERSION_PREFIX}${VERSION_MAJOR_MINOR}.${VERSION_PATCH}"
         echo "Generated new tag: $NEW_TAG"
         echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Push Git Tag
        run: |
         git config user.name "GitHub Actions"
         git config user.email "github-actions@users.noreply.github.com"
         git tag $NEW_TAG
         git push dockerit571/project:$NEW_TAG
      
      #- name: Push Docker image to Docker Hub
      #  run: docker push dockerit571/project1:latest
